[package]
name = "debris"
version = "0.1.0"
edition = "2021"
description = "the data structure"
license = "(MIT OR Apache-2.0) AND Anti-996"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
