[package]
name = "debris"
version = "0.1.1"
edition = "2021"
description = "the data structure"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
